<h2 align = center>Installation of packages in Jupyter</h3>

In [1]:
!pip install numpy
!pip install matplotlib
!pip install seaborn

You should consider upgrading via the 'pip install --upgrade pip' command.
You should consider upgrading via the 'pip install --upgrade pip' command.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np #numerical python
import matplotlib.pyplot as plt #Data Visualization
import seaborn as sns #Data Visualization

In [3]:
import numpy
Scalar = numpy.array(10)

In [4]:
Scalar

array(10)

In [5]:
Scalar_1 = np.array(10)

In [6]:
Scalar_1

array(10)

<img src='https://lh3.googleusercontent.com/-hS8OZl1ufyE/Xj6MO9feUhI/AAAAAAAAmqU/yZE9InbyTUEMjbJRJFJEX2ePziO4r7UfACK8BGAsYHg/s0/2020-02-08.png'/>

### 1. Scalar

In [7]:
Scalar.shape # Shape of the scalar

()

In [8]:
Scalar.ndim #No. of rows n column or no. of Dim

0

In [9]:
Scalar.dtype # How to find data type

dtype('int64')

In [10]:
Scalar.dtype.name # another way to find data type

'int64'

In [11]:
Scalar.data #To find memory address

In [12]:
Scalar.itemsize # finds the size of each item in memory

8

In [13]:
Scalar.size # How many element/items are there 

1

In [14]:
Scalar.astype(float) #As type is used to convert data from data to float

array(10.)

In [15]:
Scalar.astype(complex)

array(10.+0.j)

In [16]:
np.ScalarType

(int,
 float,
 complex,
 int,
 bool,
 bytes,
 str,
 memoryview,
 numpy.uint64,
 numpy.int64,
 numpy.void,
 numpy.complex256,
 numpy.float128,
 numpy.uint64,
 numpy.int64,
 numpy.str_,
 numpy.complex128,
 numpy.float64,
 numpy.uint32,
 numpy.int32,
 numpy.bytes_,
 numpy.complex64,
 numpy.float32,
 numpy.uint16,
 numpy.int16,
 numpy.bool_,
 numpy.timedelta64,
 numpy.float16,
 numpy.uint8,
 numpy.int8,
 numpy.object_,
 numpy.datetime64)

np.[Tab]

### Vector

In [17]:
Vector = np.array([10, 20, 30])
Vector

array([10, 20, 30])

In [18]:
Vector.shape

(3,)

In [19]:
Vector.ndim

1

In [20]:
Vector.itemsize

8

In [21]:
Vector.size

3

In [22]:
Vector.dtype

dtype('int64')

In [23]:
Vector.astype(np.complex128)

array([10.+0.j, 20.+0.j, 30.+0.j])

In [24]:
Vector

array([10, 20, 30])

In [25]:
Vector.T #Vector created in column

array([10, 20, 30])

In [26]:
Vector[0] #indexing

10

In [27]:
Vector[0:2] #Slicing

array([10, 20])

In [28]:
Vector[::-1] #Extended slicing

array([30, 20, 10])

### 16FEB20
While loop

In [29]:
x = 10
while x < 20:
    print(x)
    break

10


In [30]:
while x <= 20:
    print(x)
    x+=1

10
11
12
13
14
15
16
17
18
19
20


In [31]:
x = 10
while x <= 20:
    print(x)
    x+=1
    break

10


In [32]:
i = 1
while i <= 10:
    print(i**2)
    i+=1

1
4
9
16
25
36
49
64
81
100


How to write a code for tables

In [ ]:
i = int(input("Enter the no."))
j = int(input("Enter the no."))
while table > 0 and j > 0:
    print(i, "*", j, "=" "table * j")
    

### Count the number of digits in integer

In [ ]:
n = int(input("Enter the no."))
length = 0
while n >0:
    n//=10
    length += 1
    print(Length)